# Generated by Django 4.1.7 on 2024-07-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0002_alter_userex_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userex',
            name='gender',
            field=models.CharField(max_length=15),
        ),
    ]
