# Generated by Django 4.1.7 on 2024-07-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userRegistration', '0003_alter_userex_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userex',
            name='bank_name',
            field=models.CharField(default='Default', max_length=100),
        ),
    ]
